backend:
  name: github
  repo: lalaqdland/CapooTech-OfficialSite
  branch: main
  base_url: https://capootech.com/cms-auth

media_folder: "images/capoo"
public_folder: "/images/capoo"

# 这里定义了我们对 data/photos.json 文件的直接网页版控制权限
collections:
  - name: "site_data"
    label: "Site Content"
    files:
      - file: "data/photos.json"
        label: "Cat Gallery"
        name: "photos"
        fields:
          - name: "gallery"
            label: "🌟 Cat Photos (在这里管理主页的轮播照片)"
            widget: "list"
            fields:
              - {name: "url", label: "Image", widget: "image"}
